services:
  app:
    build: .
    container_name: ota-server
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - shared_network

networks:
  shared_network:
    name: db-network
    external: true
